package com.cotescu.radu.cinebook.model.backend;

import org.eclipse.persistence.indirection.ValueHolder;
import org.eclipse.persistence.indirection.ValueHolderInterface;

/**
 *  ###  Generated by EclipseLink Project EclipseLink Workbench 2.1.2 - Mon Dec 27 23:01:08 EET 2010.  ###
 */

public class Booking {

	private int id;
	private int movieUserRating;
	private ValueHolderInterface scheduleEntry;
	private int seats;
	private int status;
	private ValueHolderInterface user;

public Booking() {
	this.scheduleEntry = new ValueHolder();
	this.user = new ValueHolder();
}

public int getId() {
	return this.id;
}

public int getMovieUserRating() {
	return this.movieUserRating;
}

public Schedule getScheduleEntry() {
	// Fill in method body here.
	return null;
}

protected ValueHolderInterface getScheduleEntryHolder() {
	return this.scheduleEntry;
}

public int getSeats() {
	return this.seats;
}

public int getStatus() {
	return this.status;
}

public User getUser() {
	// Fill in method body here.
	return null;
}

protected ValueHolderInterface getUserHolder() {
	return this.user;
}

public void setId(int id) {
	this.id = id;
}

public void setMovieUserRating(int movieUserRating) {
	this.movieUserRating = movieUserRating;
}

public void setScheduleEntry(Schedule scheduleEntry) {
	this.scheduleEntry.setValue(scheduleEntry);
}

public void setScheduleEntry(ValueHolderInterface scheduleEntry) {
	this.scheduleEntry = scheduleEntry;
}

public void setSeats(int seats) {
	this.seats = seats;
}

public void setStatus(int status) {
	this.status = status;
}

public void setUser(User user) {
	this.user.setValue(user);
}

public void setUser(ValueHolderInterface user) {
	this.user = user;
}

}
