package com.cotescu.radu.cinebook.model.backend;

import java.util.Date;
import org.eclipse.persistence.indirection.ValueHolder;
import org.eclipse.persistence.indirection.ValueHolderInterface;

/**
 *  ###  Generated by EclipseLink Project EclipseLink Workbench 2.1.2 - Mon Dec 27 23:01:08 EET 2010.  ###
 */

public class MovieComment {

	private String commentText;
	private Date datePosted;
	private int id;
	private ValueHolderInterface movie;
	private ValueHolderInterface user;

public MovieComment() {
	this.movie = new ValueHolder();
	this.user = new ValueHolder();
}

public String getCommentText() {
	return this.commentText;
}

public Date getDatePosted() {
	return this.datePosted;
}

public int getId() {
	return this.id;
}

public ValueHolderInterface getMovie() {
	return this.movie;
}

public ValueHolderInterface getUser() {
	return this.user;
}

public void setCommentText(String commentText) {
	this.commentText = commentText;
}

public void setDatePosted(Date datePosted) {
	this.datePosted = datePosted;
}

public void setId(int id) {
	this.id = id;
}

public void setMovie(ValueHolderInterface movie) {
	this.movie = movie;
}

public void setUser(ValueHolderInterface user) {
	this.user = user;
}

}
