package com.cotescu.radu.cinebook.model.backend;

/**
 *  ###  Generated by EclipseLink Project EclipseLink Workbench 2.1.2 - Mon Dec 27 23:01:08 EET 2010.  ###
 */

public class Movie {

	private String cast;
	public Object comments;
	private String description;
	private String director;
	private int duration;
	private String genre;
	private int id;
	private String posterLocation;
	private String rating;
	private String title;
	private float userRating;

public Movie() {
}

public String getCast() {
	return this.cast;
}

public String getDescription() {
	return this.description;
}

public String getDirector() {
	return this.director;
}

public int getDuration() {
	return this.duration;
}

public String getGenre() {
	return this.genre;
}

public int getId() {
	return this.id;
}

public String getPosterLocation() {
	return this.posterLocation;
}

public String getRating() {
	return this.rating;
}

public String getTitle() {
	return this.title;
}

public float getUserRating() {
	return this.userRating;
}

public void setCast(String cast) {
	this.cast = cast;
}

public void setDescription(String description) {
	this.description = description;
}

public void setDirector(String director) {
	this.director = director;
}

public void setDuration(int duration) {
	this.duration = duration;
}

public void setGenre(String genre) {
	this.genre = genre;
}

public void setId(int id) {
	this.id = id;
}

public void setPosterLocation(String posterLocation) {
	this.posterLocation = posterLocation;
}

public void setRating(String rating) {
	this.rating = rating;
}

public void setTitle(String title) {
	this.title = title;
}

public void setUserRating(float userRating) {
	this.userRating = userRating;
}

}
