package com.cotescu.radu.cinebook.model.backend;

import org.eclipse.persistence.indirection.ValueHolder;
import org.eclipse.persistence.indirection.ValueHolderInterface;

/**
 *  ###  Generated by EclipseLink Project EclipseLink Workbench 2.1.2 - Tue Dec 28 15:32:46 EET 2010.  ###
 */

public class UserComment {

	private String commentText;
	private float rating;
	private ValueHolderInterface postedto;
	private ValueHolderInterface postedby;
	private int id;

public UserComment() {
	this.postedby = new ValueHolder();
	this.postedto = new ValueHolder();
}

public String getCommentText() {
	return this.commentText;
}

public int getId() {
	return this.id;
}

public User getPostedby() {
	// Fill in method body here.
	return null;
}

protected ValueHolderInterface getPostedbyHolder() {
	return this.postedby;
}

public User getPostedto() {
	// Fill in method body here.
	return null;
}

protected ValueHolderInterface getPostedtoHolder() {
	return this.postedto;
}

public float getRating() {
	return this.rating;
}

public void setCommentText(String commentText) {
	this.commentText = commentText;
}

public void setId(int id) {
	this.id = id;
}

public void setPostedby(ValueHolderInterface postedby) {
	this.postedby = postedby;
}

public void setPostedby(User postedby) {
	this.postedby.setValue(postedby);
}

public void setPostedto(ValueHolderInterface postedto) {
	this.postedto = postedto;
}

public void setPostedto(User postedto) {
	this.postedto.setValue(postedto);
}

public void setRating(float rating) {
	this.rating = rating;
}

}
