package com.cotescu.radu.cinebook.model.backend;

/**
 *  ###  Generated by EclipseLink Project EclipseLink Workbench 2.1.2 - Mon Dec 27 23:08:38 EET 2010.  ###
 */

public class User {

	private String email;
	private String firstName;
	private int id;
	private String lastName;
	private String password;
	private int role;

public User() {
}

public String getEmail() {
	return this.email;
}

public String getFirstName() {
	return this.firstName;
}

public int getId() {
	return this.id;
}

public String getLastName() {
	return this.lastName;
}

public String getPassword() {
	return this.password;
}

public int getRole() {
	return this.role;
}

public void setEmail(String email) {
	this.email = email;
}

public void setFirstName(String firstName) {
	this.firstName = firstName;
}

public void setId(int id) {
	this.id = id;
}

public void setLastName(String lastName) {
	this.lastName = lastName;
}

public void setPassword(String password) {
	this.password = password;
}

public void setRole(int role) {
	this.role = role;
}

}
