SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `cinebook`.`User` DROP COLUMN `password` , ADD COLUMN `password` VARCHAR(45) NOT NULL  AFTER `id` ;

ALTER TABLE `cinebook`.`Schedule` 
DROP INDEX `fk_Schedule_Movie` 
, ADD INDEX `fk_Schedule_Movie` (`movie` ASC) ;

ALTER TABLE `cinebook`.`MovieComment` 
DROP INDEX `id_UNIQUE` 
, ADD UNIQUE INDEX `id_UNIQUE` (`id` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
