package uk.ac.soton.ecs.rdc1g10.cinebook.model.backend;

import org.eclipse.persistence.indirection.ValueHolder;
import org.eclipse.persistence.indirection.ValueHolderInterface;

/**
 *  ###  Generated by EclipseLink Project EclipseLink Workbench 2.1.2 - Fri Jan 07 19:08:32 GMT 2011.  ###
 */

public class Booking {

	private Integer id;
	private ValueHolderInterface scheduleEntry;
	private Integer seats;
	private Integer status;
	private ValueHolderInterface user;

public Booking() {
	this.scheduleEntry = new ValueHolder();
	this.user = new ValueHolder();
}

public Integer getId() {
	return this.id;
}

public Schedule getScheduleEntry() {
	return (Schedule) getScheduleEntryHolder().getValue();
}

protected ValueHolderInterface getScheduleEntryHolder() {
	return this.scheduleEntry;
}

public Integer getSeats() {
	return this.seats;
}

public Integer getStatus() {
	return this.status;
}

public User getUser() {
	return (User) getUserHolder().getValue();
}

protected ValueHolderInterface getUserHolder() {
	return this.user;
}

public void setId(Integer id) {
	this.id = id;
}

public void setScheduleEntry(ValueHolderInterface scheduleEntry) {
	this.scheduleEntry = scheduleEntry;
}

public void setScheduleEntry(Schedule scheduleEntry) {
	this.scheduleEntry.setValue(scheduleEntry);
}

public void setSeats(Integer seats) {
	this.seats = seats;
}

public void setStatus(Integer status) {
	this.status = status;
}

public void setUser(ValueHolderInterface user) {
	this.user = user;
}

public void setUser(User user) {
	this.user.setValue(user);
}

}
