package uk.ac.soton.ecs.rdc1g10.cinebook.model.backend;

import org.eclipse.persistence.indirection.ValueHolder;
import org.eclipse.persistence.indirection.ValueHolderInterface;

/**
 *  ###  Generated by EclipseLink Project EclipseLink Workbench 2.1.2 - Mon Jan 10 14:15:19 GMT 2011.  ###
 */

public class MovieUserRating {

	private Integer rating;
	private ValueHolderInterface movie;
	private ValueHolderInterface user;
	private Integer id;

public MovieUserRating() {
	this.movie = new ValueHolder();
	this.user = new ValueHolder();
}

public Integer getId() {
	return this.id;
}

public Movie getMovie() {
	return (Movie)getMovieHolder().getValue();
}

protected ValueHolderInterface getMovieHolder() {
	return this.movie;
}

public Integer getRating() {
	return this.rating;
}

public User getUser() {
	return (User)getUserHolder().getValue();
}

protected ValueHolderInterface getUserHolder() {
	return this.user;
}

public void setId(Integer id) {
	this.id = id;
}

public void setMovie(ValueHolderInterface movie) {
	this.movie = movie;
}

public void setMovie(Movie movie) {
	this.movie.setValue(movie);
}

public void setRating(Integer rating) {
	this.rating = rating;
}

public void setUser(ValueHolderInterface user) {
	this.user = user;
}

public void setUser(User user) {
	this.user.setValue(user);
}

}
