package uk.ac.soton.ecs.rdc1g10.cinebook.model.backend;

import java.util.Date;
import org.eclipse.persistence.indirection.ValueHolder;
import org.eclipse.persistence.indirection.ValueHolderInterface;

/**
 *  ###  Generated by EclipseLink Project EclipseLink Workbench 2.1.2 - Fri Jan 07 19:07:11 GMT 2011.  ###
 */

public class MovieComment {

	private String commentText;
	private Date datePosted;
	private Integer id;
	private ValueHolderInterface movie;
	private ValueHolderInterface user;

public MovieComment() {
	this.movie = new ValueHolder();
	this.user = new ValueHolder();
}

public String getCommentText() {
	return this.commentText;
}

public Date getDatePosted() {
	return this.datePosted;
}

public Integer getId() {
	return this.id;
}

public ValueHolderInterface getMovie() {
	return this.movie;
}

public ValueHolderInterface getUser() {
	return this.user;
}

public void setCommentText(String commentText) {
	this.commentText = commentText;
}

public void setDatePosted(Date datePosted) {
	this.datePosted = datePosted;
}

public void setId(Integer id) {
	this.id = id;
}

public void setMovie(ValueHolderInterface movie) {
	this.movie = movie;
}

public void setUser(ValueHolderInterface user) {
	this.user = user;
}

}
