package uk.ac.soton.ecs.rdc1g10.cinebook.model.backend;

import java.util.Calendar;
import org.eclipse.persistence.indirection.ValueHolder;
import org.eclipse.persistence.indirection.ValueHolderInterface;

/**
 *  ###  Generated by EclipseLink Project EclipseLink Workbench 2.1.2 - Mon Jan 03 13:15:03 EET 2011.  ###
 */

public class Schedule {

	private int id;
	private ValueHolderInterface movie;
	private Calendar startTime;
	private int theatre;

public Schedule() {
	this.movie = new ValueHolder();
}

public int getId() {
	return this.id;
}

public Movie getMovie() {
	// Fill in method body here.
	return null;
}

protected ValueHolderInterface getMovieHolder() {
	return this.movie;
}

public Calendar getStartTime() {
	return this.startTime;
}

public int getTheatre() {
	return this.theatre;
}

public void setId(int id) {
	this.id = id;
}

public void setMovie(Movie movie) {
	this.movie.setValue(movie);
}

public void setMovie(ValueHolderInterface movie) {
	this.movie = movie;
}

public void setStartTime(Calendar startTime) {
	this.startTime = startTime;
}

public void setTheatre(int theatre) {
	this.theatre = theatre;
}

}
