package uk.ac.soton.ecs.rdc1g10.cinebook.model.backend;

import java.util.Date;
import org.eclipse.persistence.indirection.ValueHolder;
import org.eclipse.persistence.indirection.ValueHolderInterface;

/**
 *  ###  Generated by EclipseLink Project EclipseLink Workbench 2.1.2 - Fri Jan 07 19:07:11 GMT 2011.  ###
 */

public class UserComment {

	private String commentText;
	private Date datePosted;
	private Integer id;
	private ValueHolderInterface postedby;
	private ValueHolderInterface postedto;
	private float rating;

public UserComment() {
	this.postedby = new ValueHolder();
	this.postedto = new ValueHolder();
}

public String getCommentText() {
	return this.commentText;
}

public Date getDatePosted() {
	return this.datePosted;
}

public Integer getId() {
	return this.id;
}

public User getPostedby() {
	return (User)getPostedbyHolder().getValue();
}

protected ValueHolderInterface getPostedbyHolder() {
	return this.postedby;
}

public User getPostedto() {
	return (User)getPostedtoHolder().getValue();
}

protected ValueHolderInterface getPostedtoHolder() {
	return this.postedto;
}

public float getRating() {
	return this.rating;
}

public void setCommentText(String commentText) {
	this.commentText = commentText;
}

public void setDatePosted(Date datePosted) {
	this.datePosted = datePosted;
}

public void setId(Integer id) {
	this.id = id;
}

public void setPostedby(ValueHolderInterface postedby) {
	this.postedby = postedby;
}

public void setPostedby(User postedby) {
	this.postedby.setValue(postedby);
}

public void setPostedto(ValueHolderInterface postedto) {
	this.postedto = postedto;
}

public void setPostedto(User postedto) {
	this.postedto.setValue(postedto);
}

public void setRating(float rating) {
	this.rating = rating;
}

}
