package uk.ac.soton.ecs.rdc1g10.cinebook.model.backend;

/**
 *  ###  Generated by EclipseLink Project EclipseLink Workbench 2.1.2 - Fri Jan 07 19:07:11 GMT 2011.  ###
 */

public class User {

	private String email;
	private String firstName;
	private Integer id;
	private String lastName;
	private String password;
	private Integer role;

public User() {
}

public String getEmail() {
	return this.email;
}

public String getFirstName() {
	return this.firstName;
}

public Integer getId() {
	return this.id;
}

public String getLastName() {
	return this.lastName;
}

public String getPassword() {
	return this.password;
}

public Integer getRole() {
	return this.role;
}

public void setEmail(String email) {
	this.email = email;
}

public void setFirstName(String firstName) {
	this.firstName = firstName;
}

public void setId(Integer id) {
	this.id = id;
}

public void setLastName(String lastName) {
	this.lastName = lastName;
}

public void setPassword(String password) {
	this.password = password;
}

public void setRole(Integer role) {
	this.role = role;
}

}
